// One-off: download the Thai + Latin subsets of the app's Google Fonts into assets/fonts
// so the offline build can embed them. Fonts are under the SIL Open Font License.
import { writeFileSync } from 'node:fs';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Mitr:wght@400;500;600&family=IBM+Plex+Sans+Thai:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'user-agent': UA } })).text();
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face \{[^}]+\})/g)].filter(([, subset]) => subset === 'thai' || subset === 'latin');
let out = '/* Generated by scripts/fetch-fonts.mjs (SIL Open Font License) */\n';
for (const [, subset, block] of blocks) {
  const family = block.match(/font-family: '([^']+)'/)[1];
  const weight = block.match(/font-weight: (\d+)/)[1];
  const url = block.match(/url\(([^)]+)\)/)[1];
  const file = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`;
  writeFileSync(`assets/fonts/${file}`, Buffer.from(await (await fetch(url)).arrayBuffer()));
  out += `/* ${subset} */\n${block.replace(/url\([^)]+\)/, `url(${file})`)}\n`;
}
writeFileSync('assets/fonts/fonts.css', out);
console.log(`saved ${blocks.length} font files`);
